error: Node `foo` is part of a dependency cycle
 --> tests/fail/ui/causality/cycle-node.rs:2:5
  |
2 | /     node foo(i : int) returns (o : int);
3 | |     let o = bar(i); tel;
  | |_______________________^
